### ISSUE TITLE
sshdo fails if run twice in the same minute

### ISSUE THREAD

**Issue by jimneumann** [khrpcek/sshdo#2]
me@box1:~/sshdo# ./sshdo.py 
Servers: boxen.txt
Command: service nagios-nrpe-server restart
Traceback (most recent call last):
  File "./sshdo.py", line 26, in <module>
    print sshdo()
  File "/home/me/sshdo/sshdef.py", line 52, in sshdo
    if not os.path.exists('logs'+datetime): os.makedirs('logs/'+datetime)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: 'logs/05022015-0116'

**Comment by khrpcek** [comment]
I added seconds to the log file names so that it can be run multiple times per minute without falling over its own log files.
